import MarkDown from "react-markdown";
import { IMAGE_TO_TEXT_MODELS } from "../../constants";
import { ChatMetaData } from "../chat-metadata/ChatMetaData";
import "./MessageResponse.css";

interface MessageResponseProps {
  responses: any;
  metaData: any;
}

export const MessageResponse = ({
  responses,
  metaData,
}: MessageResponseProps) => {
  return (
    <div>
      <div className="bot-item-container">
        <div className="bot-item">
          <div className="bot-type-title">{`Generated By ${IMAGE_TO_TEXT_MODELS.GPT_4O_MINI}`}</div>
          <MarkDown>{responses[IMAGE_TO_TEXT_MODELS.GPT_4O_MINI]}</MarkDown>
        </div>
        <div className="bot-item">
          <div className="bot-type-title">{`Generated By ${IMAGE_TO_TEXT_MODELS.GPT_4_O}`}</div>
          <MarkDown>{responses[IMAGE_TO_TEXT_MODELS.GPT_4_O]}</MarkDown>
        </div>
      </div>
      <ChatMetaData {...metaData} />
    </div>
  );
};
